Repository KDT-NES/NES, pull requests merged in 2022-12, with the labels that each got.

#62 feat: Q&A 페이지 생성 #62
  accounts/views.py
  config/urls.py
  questions/models.py
  questions/templates/questions/create.html
  questions/templates/questions/index.html
  questions/urls.py
  questions/views.py
Labels: 💻 기능 구현, 💜 백엔드

#73 feat: 작가 이메일 인증, 문의, 쪽지 기능 구현 #71
  accounts/models.py
  accounts/templates/accounts/check_artist.html
  accounts/templates/accounts/profile.html
  accounts/urls.py
  accounts/views.py
  questions/forms.py
  questions/migrations/0001_initial.py
  questions/models.py
  questions/templates/questions/create.html
  questions/templates/questions/index.html
  questions/templates/questions/myquestion.html
  questions/urls.py
  questions/views.py
Labels: 💻 기능 구현, 💜 백엔드

#74 feat: notes 페이지에 페이지네이션 추가 #74
  notes/templates/notes/index.html
  notes/views.py
Labels: 💻 기능 구현, 💜 백엔드

#76 feat: base2 화면 구현 #72
  static/style/base2.css
  templates/base2.html
Labels: 💙 프론트엔드

#80 fix: info.html 장바구니 버튼 수정 #79
  accounts/migrations/0002_alter_user_profileimage.py
  orders/templates/orders/info.html
  orders/views.py
  questions/migrations/0002_alter_question_image.py
Labels: 🐛 버그, 💜 백엔드

#82 feat: 보낸DM, 받은DM 모달기능 추가 #81
  notes/migrations/0002_notes_text.py
  notes/models.py
  notes/templates/notes/index.html
  notes/views.py
  templates/base.html
Labels: 💻 기능 구현, 💜 백엔드

#87 feat: 편지함 비동기 처리 및 모달생성 #86
  notes/templates/notes/index.html
  notes/views.py
  static/images/1.jpg
  templates/base.html
Labels: 💻 기능 구현, 💜 백엔드

#89 feat: profile에서 링크 설정 및 조건문 추가 #88
  accounts/templates/accounts/profile.html
Labels: 💻 기능 구현, 💜 백엔드

#90 feat: 카카오 로그인시 추가정보 입력을 위해 페이지 이동 추가 #90
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_user_profileimage.py
  accounts/templates/accounts/kakao_signup.html
  accounts/urls.py
  accounts/views.py
Labels: 💻 기능 구현, 💜 백엔드

#94 feat: 카카오 로그인 로직 재설정 #94
  accounts/views.py
Labels: 💻 기능 구현, 💜 백엔드

#104 feat: 편지함 페이지네이션 구분 #104
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/kakao_signup.html
  accounts/templates/accounts/profile.html
  accounts/urls.py
  articles/migrations/0001_initial.py
  notes/migrations/0001_initial.py
  notes/templates/notes/index.html
  notes/urls.py
  notes/views.py
  orders/migrations/0001_initial.py
  questions/migrations/0001_initial.py
Labels: 💻 기능 구현, 💜 백엔드

#105 fix: profile 페이지 높이 수정
  accounts/templates/accounts/profile.html
  static/style/profile.css
Labels: 💙 프론트엔드, 💩 수정

#107 feat: 디테일 화면 구현 #96
  articles/templates/articles/datail2.html
  static/script/articles_detail.js
  static/style/articles_detail.css
Labels: 💻 기능 구현, 💙 프론트엔드

#109 feat: 디테일 페이지 미디어쿼리 화면 구현 #108
  static/style/articles_detail.css
Labels: 💻 기능 구현, 💙 프론트엔드

#110 처음 카카오 회원가입시 email값 입력 및 저장 구현 #110
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/kakao_signup.html
  accounts/views.py
  notes/migrations/0001_initial.py
  notes/templates/notes/index.html
  notes/views.py
Labels: 💻 기능 구현, 💜 백엔드

#115 feat: index 이미지 수정 및 소개 박스 위치 이동
  articles/templates/articles/index.html
  static/style/articles_index.css
Labels: 💻 기능 구현, 💙 프론트엔드, 💩 수정

#118 feat: 티켓 화면 구현 #117
  static/style/ticket.css
  templates/ticket.html
Labels: 💻 기능 구현, 💙 프론트엔드

#122 feat: 편지 삭제 비동기 구현 #122
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/signup.html
  accounts/views.py
  notes/templates/notes/index.html
  notes/views.py
  templates/base.html
Labels: 💻 기능 구현, 💜 백엔드

#123 feat: 편지함 로직 재설정 #123
  notes/templates/notes/index.html
  notes/templates/notes/send.html
Labels: 💜 백엔드, 💩 수정

#126 fix: articles main 화면 깨짐 수정 #119
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  articles/templates/articles/main.html
  notes/migrations/0001_initial.py
  orders/migrations/0001_initial.py
  questions/migrations/0001_initial.py
  static/style/base2.css
  static/style/main.css
  templates/base2.html
Labels: 💙 프론트엔드, 💩 수정

#128 fix: accounts 버그 수정 및 코드 리팩토링 # 127
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/profile.html
  accounts/views.py
  config/settings.py
  images/고민즁.jpg
  images/구지만씨.jpg
  images/구지만씨_49ITdxS.jpg
  images/심쿵.jpg
  images/쓸쓸.jpg
  images/안보이네.jpg
  images/저말인가여.jpg
  images/제목_없는_아트워크_10000.jpg
  images/충격.jpg
  images/하트뿅뿅.jpg
  images/헤헤.jpg
Labels: 💜 백엔드, 💩 수정

#129 feat: articles index 사진 카테고리 추가 #127
  articles/templates/articles/index.html
  articles/templates/articles/main2.html
  static/style/articles_index.css
  static/style/base2.css
  templates/base2.html
Labels: 💻 기능 구현, 💙 프론트엔드, 💩 수정

#135 feat: 티켓 머신 구현 #130
  static/script/ticket_machine.js
  static/style/ticket_machine.css
  templates/ticket_machine.html
Labels: 💻 기능 구현, 💙 프론트엔드

#139 fix: articles main 페이지네이션, 사진 수정 #131
  images/20220316_p1.jpg
  images/39DD1EF5-5BAD-4CEE-B586-79A90675328D.jpeg
  images/IMG_20190210_012450.jpeg
  images/다운로드.jpeg
  images/다운로드.jpg
  images/스크린샷_2021-04-04_오후_1.53.07.jpg
  images/스크린샷_2022-11-21_오후_3.07.01.jpg
  static/style/main.css
Labels: 💙 프론트엔드, 💩 수정

#150 fix: articles 메인 페이지네이션 수정 #149
  articles/templates/articles/main.html
  articles/templates/articles/search.html
  images/IMG_2287.jpeg
  images/마찌_찌부브라우니pc배경화면.jpg
Labels: 💙 프론트엔드, 💩 수정

#152 feat: articles에 nav링크 연결 #151
  accounts/templates/accounts/kakao_signup.html
  articles/templates/articles/main.html
  orders/migrations/0006_alter_order_requests.py
Labels: 💙 프론트엔드

#154 fix: search menu 수정 #151
  articles/templates/articles/search.html
  static/style/main.css
Labels: 💙 프론트엔드, 💩 수정

#162 feat: 프로필 작가 인증시 작품등록, 인증마크 비동기 구현 #162
  accounts/forms.py
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/signup.html
  accounts/views.py
Labels: 💻 기능 구현, 💙 프론트엔드, 💜 백엔드

#163 feat: articles detail 연결 #158
  articles/templates/articles/detail.html
  images/스크린샷_2022-09-29_오후_1.39.09.jpg
  static/style/articles_detail.css
Labels: 💻 기능 구현, 💙 프론트엔드

#164 feat: accounts에서 작가 등록시 인증마크, 작품등록 비동기 처리 #164
  accounts/forms.py
  accounts/migrations/0004_auto_20221207_1608.py
  accounts/migrations/0005_rename_instargram_user_instagram.py
  accounts/models.py
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/social_update.html
  accounts/urls.py
  accounts/views.py
  images/심쿵_E2sSDAs.jpg
Labels: 💻 기능 구현, 💙 프론트엔드

#169 feat: 문의페이지 비동기 댓글 추가 #168
  images/덜덜.png
  orders/migrations/0002_alter_order_requests.py
  questions/forms.py
  questions/migrations/0002_comment.py
  questions/models.py
  questions/templates/questions/myquestion.html
  questions/urls.py
  questions/views.py
Labels: 💻 기능 구현, 💜 백엔드

#171 feat: 슈퍼유저 생성 #171
  questions/admin.py
Labels: 💜 백엔드

#176 feat: 소셜 로그인 DB저장 및 링크설정 #175
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/social_update.html
  accounts/views.py
Labels: 💜 백엔드

#181 fix: orders info 규격 수정 #178
  orders/templates/orders/info.html
  static/style/info.css
Labels: 💙 프론트엔드, 💩 수정

#189 feat: 댓글쓰기 로그인 관련
  articles/templates/articles/detail.html
  articles/views.py
Labels: 💜 백엔드, 💩 수정

#193 fix: 디자인 오류 수정
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  articles/migrations/0002_alter_art_likes.py
  articles/migrations/0003_alter_art_likes.py
  articles/templates/articles/datail2.html
  articles/templates/articles/detail.html
  notes/migrations/0001_initial.py
  orders/migrations/0001_initial.py
  questions/migrations/0001_initial.py
  questions/migrations/0004_alter_question_user.py
  static/style/articles_detail.css
  static/style/info.css
Labels: 💙 프론트엔드, 💩 수정

#197 feat: questions 페이지 댓글기능 오류수정, admin 댓글작성 가능 추가 #197
  accounts/views.py
  questions/templates/questions/adminqna.html
  questions/templates/questions/index.html
  questions/templates/questions/myquestion.html
  questions/views.py
Labels: 💻 기능 구현, 💜 백엔드

#199 feat: accounts 페이지네이션 작품 메인과 동일하게 수정 #198
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/profile.html
  accounts/views.py
  articles/migrations/0001_initial.py
  articles/migrations/0002_art_order.py
  articles/migrations/0003_alter_art_order.py
  images/고민즁_hOa4aUG.jpg
  images/분노_Wex3Py5.png
  images/쑥스.jpg
  images/쑥스_ThRtLV1.png
  images/안보이네_pDu06G0.jpg
  notes/migrations/0001_initial.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_order_arts.py
  questions/migrations/0001_initial.py
Labels: 💩 수정

#203 feat: profile페이지 좋아요 작품 출력 #201
  accounts/templates/accounts/profile.html
  accounts/views.py
Labels: 💻 기능 구현, 💜 백엔드

#204 feat: orders/info 사진 클릭 시 확대
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  articles/migrations/0002_art_order.py
  images/111_BgyQ4gO.jpg
  images/화면_캡처_2022-10-03_205734_hO0iUFE.jpg
  images/화면_캡처_2022-11-24_051059_VOhaKlp.jpg
  images/화면_캡처_2022-11-24_051059_qtT0TPy.jpg
  notes/migrations/0001_initial.py
  orders/migrations/0001_initial.py
  orders/templates/orders/info.html
  orders/templates/orders/mycart.html
  questions/migrations/0001_initial.py
  static/style/cart.css
  static/style/info.css
  templates/base.html
Labels: 💻 기능 구현, 💙 프론트엔드

#208 feat: profile 장바구니 출력 추가 #208
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/social_update.html
  accounts/views.py
  images/일단의심.jpg
Labels: 💻 기능 구현, 💜 백엔드

#209 fix: 결제 완료 페이지 규격 수정 #194
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  articles/migrations/0002_art_order.py
  images/스크린샷_2022-11-21_오후_3.07.01_PXWKHAr.jpg
  images/스크린샷_2022-11-21_오후_3.07.01_uj2D3mw.jpg
  notes/migrations/0001_initial.py
  orders/migrations/0001_initial.py
  orders/templates/orders/complete.html
  orders/templates/orders/payment.html
  questions/migrations/0001_initial.py
  static/style/complete.css
Labels: 💙 프론트엔드, 💩 수정

#211 feat: notes쪽 accounts 네이밍변경 #211
  notes/templates/notes/index.html
  notes/templates/notes/send.html
Labels: 💜 백엔드, 💩 수정

#212 feat: questions 페이지 유저네이밍 재설정 #212
  images/쑥스_y98Wzre.png
  questions/templates/questions/adminqna.html
  questions/templates/questions/myquestion.html
  questions/views.py
Labels: 💜 백엔드, 💩 수정

#213 feat: articles의 detail 댓글 네이밍 재설정 #213
  articles/templates/articles/detail.html
  articles/views.py
Labels: 💜 백엔드, 💩 수정

#215 feat: accounts 프로필 페이지네이션 #215
  accounts/templates/accounts/check_artist.html
  accounts/templates/accounts/kakao_signup.html
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/profile_update.html
  accounts/templates/accounts/send_valid_number.html
  accounts/templates/accounts/signup.html
  accounts/views.py
  images/심쿵_2JB1ljc.jpg
  images/안녕_2TsyZpY.jpg
  images/안보이네.png
  images/헤헤_U7BxDBb.jpg
Labels: 💜 백엔드

#216 feat: offer 모델 추가 #216
  articles/forms.py
  articles/models.py
  orders/templates/orders/offer.html
  orders/urls.py
  orders/views.py
Labels: 💻 기능 구현, 💜 백엔드

#218 feat: offers url, model 추가 #218
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  articles/migrations/0002_art_order.py
  articles/models.py
  notes/migrations/0001_initial.py
  orders/migrations/0001_initial.py
  orders/urls.py
  orders/views.py
Labels: 💜 백엔드

#226 feat: 최근 본 작품 모델하고 로직 추가
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/login.html
  accounts/views.py
  articles/migrations/0001_initial.py
  articles/migrations/0002_art_order.py
  articles/templates/articles/create.html
  articles/templates/articles/index.html
  articles/templates/articles/main.html
  articles/views.py
  images/111_GqW6IQc.jpg
  images/111_nLmVikI.jpg
  images/111_qVNGUOj.jpg
  images/111_wRDgvie.jpg
  images/logo.jpg
  images/마법의모자_nedMbFg.jpg
  images/양세마리_5w2s4qr.jpg
  images/양세마리_V6lpm2F.jpg
  images/양세마리_Y6CBhcj.jpg
  images/양세마리_zgqghmn.jpg
  images/화면_캡처_2022-10-03_205734_57fTb25.jpg
  images/화면_캡처_2022-11-24_051059_6JLNuo5.jpg
  images/화면_캡처_2022-11-24_051059_6WkKYZ5.jpg
  images/화면_캡처_2022-11-24_051059_o3QcuFG.jpg
  notes/migrations/0001_initial.py
  orders/migrations/0001_initial.py
  questions/migrations/0001_initial.py
Labels: 💻 기능 구현, 💜 백엔드

#227 feat: offer에서 가격제안 수락 버튼 클릭 시 alert 뜨게 구현 #227
  orders/templates/orders/offer.html
  orders/views.py
Labels: 💻 기능 구현, 💜 백엔드

#229 feat: accounts 작가 인증 다시보내기 오류 수정 #229
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/profile.html
  accounts/views.py
  articles/migrations/0001_initial.py
  articles/migrations/0002_art_order.py
  images/안녕_6E4Dkr4.jpg
  notes/migrations/0001_initial.py
  orders/migrations/0001_initial.py
  questions/migrations/0001_initial.py
Labels: 💜 백엔드, 💩 수정

#237 fix: sweetalert 색 변경 + 최근작품 반응형 약간
  accounts/templates/accounts/login.html
  accounts/templates/accounts/recently.html
  articles/templates/articles/main.html
  orders/templates/orders/mycart.html
  static/style/recently.css
Labels: 💙 프론트엔드, 💩 수정

#240 feat: accounts페이지 카테고리탭 완성 #240
  accounts/templates/accounts/profile.html
  accounts/views.py
  images/쑥스_BjP7qA5.jpg
  images/헤헤_ykx1pkF.jpg
Labels: 💜 백엔드

#241 feat: articles/detail 결제완료 상태시 soldout 표시 #241
  articles/templates/articles/detail.html
Labels: 💻 기능 구현, 💜 백엔드

#247 feat: notes/send css 수정 #246
  notes/templates/notes/send.html
Labels: 💙 프론트엔드

#248 feat: accounts페이지 판매완료 soldout표시 및 하트추가 #248
  accounts/templates/accounts/profile.html
  static/style/profile.css
Labels: 💙 프론트엔드

#252 feat: 회원가입 쪽 sweetalert 적용안된부분 적용
  accounts/templates/accounts/signup.html
  images/favicon.jpg
  scraping.py
Labels: 💻 기능 구현, 💙 프론트엔드

#256 fix: 쪽지 디테일 수정 #254
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  articles/migrations/0002_art_order.py
  images/Unknown.jpg
  images/Unknown_S6lepMW.jpg
  images/다운로드_EDRp7nY.jpeg
  images/스크린샷_2022-11-21_오후_3.07.01_1Ien3Dm.jpg
  images/스크린샷_2022-11-21_오후_3.07.01_v2NFXOL.jpg
  notes/migrations/0001_initial.py
  notes/templates/notes/send.html
  orders/migrations/0001_initial.py
  questions/migrations/0001_initial.py
  static/style/post_send.css
Labels: 💙 프론트엔드, 💩 수정

#262 feat: articles detail에 뒤로가기 버튼 추가 #262
  articles/templates/articles/detail.html
  images/쑥스_v2DT1sd.jpg
  static/style/articles_detail.css
Labels: 💙 프론트엔드

#265 feat: address 기입 창 오류 수정 #265
  accounts/templates/accounts/profile_update.html
  accounts/templates/accounts/signup.html
Labels: 🐛 버그, 💩 수정

#267 feat: 가격제안 수락시 alert 창 생성 #266
  orders/templates/orders/offer.html
Labels: 💜 백엔드

#270 fix: orders/offer, orders/mycart 알림창 문구 수정
  orders/templates/orders/mycart.html
  orders/templates/orders/offer.html
Labels: 💙 프론트엔드, 💩 수정

#272 feat: 쪽지 navbar, QnA navbar 추가 및 전체 페이지 navbar 통일 #272
  accounts/templates/accounts/profile.html
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/templates/articles/main.html
  articles/templates/articles/search.html
  notes/templates/notes/index.html
  notes/templates/notes/send.html
  orders/templates/orders/complete.html
  orders/templates/orders/mycart.html
  orders/templates/orders/offer.html
  questions/templates/questions/index.html
  static/style/articles_detail.css
  static/style/cart.css
  static/style/complete.css
  static/style/main.css
  static/style/offer.css
  static/style/post.css
  static/style/post_send.css
  static/style/profile.css
  static/style/questions.css
Labels: 💙 프론트엔드, 💩 수정

#274 feat: notes쪽 보낸편지 오류 수정 #274
  notes/templates/notes/index.html
  notes/templates/notes/send.html
Labels: 🐛 버그, 💩 수정

#275 feat: login, signup 디자인 수정 #275
  static/style/login.css
  static/style/signup.css
Labels: 💙 프론트엔드

#278 fix: 회원가입 로고 크기 수정
  static/style/signup.css
Labels: 💙 프론트엔드, 💩 수정

#284 Fix/comment alert
  accounts/templates/accounts/signup.html
  articles/templates/articles/detail.html
  articles/views.py
  static/script/comment.js
Labels: 💙 프론트엔드, 💩 수정

#286 fix: 쪽지함 반응형 수정 #282
  notes/templates/notes/index.html
  static/style/post.css
Labels: 💙 프론트엔드, 💩 수정

#287 fix: 프로필 스타일링 수정 #285
  accounts/templates/accounts/profile.html
  images/20220316_p1_gozxHId.jpg
  static/style/profile.css
Labels: 💙 프론트엔드, 💩 수정

#289 fix: 로그인, 작품 등록 스타일 수정 #288
  static/style/profile_update.css
  static/style/signup.css
Labels: 💙 프론트엔드, 💩 수정

#291 articles detail에서 작가로 이동기능 추가
  accounts/views.py
  articles/templates/articles/detail.html
Labels: 💙 프론트엔드

#292 fix: 네브바 border 수정
  orders/templates/orders/info.html
  static/style/info.css
Labels: 💙 프론트엔드, 💩 수정

#293 fix: 전체 작품 제목 추가
  articles/templates/articles/main.html
Labels: 💙 프론트엔드, 💩 수정

#294 feat: accounts 페이지네이션 제거 #294
  accounts/templates/accounts/profile.html
  accounts/views.py
  images/고민즁_1YrRctZ.jpg
  images/분노_MqnbiFa.jpg
  images/심쿵_jpJVyd4.jpg
  images/안보이네_kb8LEWF.jpg
  images/최고_v8cSAxi.jpg
  images/헤헤_0duhmuJ.jpg
  static/style/cart.css
Labels: 💙 프론트엔드, 💜 백엔드, 💩 수정

#297 feat: 아이디/비밀번호 찾기 알림창
  accounts/templates/accounts/login.html
Labels: 💻 기능 구현, 💙 프론트엔드

#301 카카오url 재설정
  accounts/views.py
Labels: 💜 백엔드

#318 feat: accounts/login
  accounts/forms.py
  accounts/templates/accounts/login.html
  accounts/templates/accounts/reset_pw.html
  accounts/urls.py
  accounts/views.py
  orders/templates/orders/offer.html
  orders/views.py
  static/style/login.css
Labels: 💻 기능 구현, 💙 프론트엔드, 💜 백엔드
