Repository KDT-NES/NES, pull requests merged in 2022-11, with the labels that each got.

#5 feat : 파일 내용 추가 #4
  test.md
Labels: 💻 기능 구현, 💙 프론트엔드

#19 feat: 스타트 페이지 화면 구현
  static/img/logo-blue.png
  static/img/logo-orange.png
  static/script/start.js
  static/style/start.css
  templates/base.html
  templates/start.html
Labels: 💻 기능 구현, 💙 프론트엔드

#26 feat: articles CRUD 구현 #20
  articles/forms.py
  articles/migrations/0001_initial.py
  articles/models.py
  articles/templates/articles/detail.html
  articles/templates/articles/forms.html
  articles/urls.py
  articles/views.py
  images/art1.jpg
  images/art1_QY6apwt.jpg
Labels: 💻 기능 구현, 💜 백엔드

#29 feat: 구매 페이지 ( 장바구니, 구매 정보 ) 추가 #28
  config/settings.py
  config/urls.py
  orders/templates/orders/basket.html
  orders/templates/orders/complete.html
  orders/templates/orders/info.html
  orders/templates/orders/payment.html
  orders/urls.py
  orders/views.py
  static/photos/pic_1.png
  static/style/base.css
  static/style/basket.css
  static/style/complete.css
  static/style/info.css
  templates/base.html
Labels: 💻 기능 구현, 💙 프론트엔드

#30 feat: Add social login #30
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/index.html
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
  articles/migrations/0002_alter_art_art_category.py
Labels: 💻 기능 구현, 💜 백엔드

#32 feat: 편지기능 추가 #32
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/signup.html
  config/settings.py
  config/urls.py
  notes/__init__.py
  notes/admin.py
  notes/apps.py
  notes/forms.py
  notes/migrations/0001_initial.py
  notes/migrations/__init__.py
  notes/models.py
  notes/templates/notes/detail.html
  notes/templates/notes/index.html
  notes/templates/notes/send.html
  notes/tests.py
  notes/urls.py
  notes/views.py
Labels: 💻 기능 구현, 💜 백엔드

#40 feat: 메인 scroll page 화면 구현 #21
  articles/templates/articles/index.html
  main/__init__.py
  main/admin.py
  main/apps.py
  main/forms.py
  main/migrations/__init__.py
  main/models.py
  main/tests.py
  main/urls.py
  main/views.py
  static/img/logo-op-blue.png
  static/style/articles_index.css
Labels: 💻 기능 구현, 💙 프론트엔드

#44 feat: 주소 입력창과 이메일 전송 기능 구현 #44
  accounts/templates/accounts/send_valid_number.html
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
  config/settings.py
Labels: 💻 기능 구현, 💜 백엔드

#45 fix: 이메일 인증 버그 수정 #45
  accounts/templates/accounts/signup.html
  orders/migrations/0002_alter_cartitem_quantity.py
Labels: 🐛 버그, 💩 수정
